version: '3.3'
services:
    pentesting:
        environment:
            - DISPLAY
        volumes:
            - '/run/user/1000/gdm/Xauthority:/root/.Xauthority'
            - /tmp/.X11-unix
            - /pentest:/pentest
        network_mode: host
        image: infosecmatt/pentesting
        stdin_open: true
        tty: true
